// IntelliVet Landing Page — Bilingual Content
// Design: Warm Editorial meets Functional Brutalism
// Fonts: Playfair Display (headlines) + Source Sans 3 (body)
// Colors: Ivory bg, Dark Green primary, WhatsApp Green CTA, Red urgency

export type Lang = "es" | "en";

export const content = {
  es: {
    lang: "es",
    langSwitch: "English",
    nav: {
      logo: "IntelliVet",
      tagline: "Responde por tu clínica 24/7",
    },
    urgencyBanner: {
      text: "OFERTA ESPECIAL — 60% DE DESCUENTO",
      sub: "Solo quedan 3 lugares este mes",
      countdown: "La oferta termina en:",
    },
    hero: {
      badge: "Más de 5 clínicas veterinarias ya confían en IntelliVet",
      headline: "Ahora mismo, alguien no recibe respuesta.",
      subheadline:
        "Cuando tu clínica no contesta WhatsApp, Instagram o llamadas, ese cliente busca otra veterinaria. IntelliVet responde por ti 24 horas al día — incluso de noche.",
      cta1: "Escríbenos por WhatsApp",
      cta1sub: "Te respondemos en menos de 1 hora",
      cta2: "Ver demo de 15 minutos",
      microcopy:
        "En menos de 1 hora te contactamos para una demo gratuita de 15 minutos — sin compromiso.",
    },
    vsl: {
      title: "Video de presentación",
      subtitle: "Próximamente",
      description:
        "En este video te mostraremos cómo una clínica puede dejar de perder llamadas, mensajes y urgencias fuera de horario — sin contratar más personal.",
    },
    pain: {
      title: "Lo que ya está pasando en tu clínica",
      items: [
        {
          icon: "phone-off",
          headline: "Suena el teléfono mientras estás en consulta.",
          body: "Nadie contesta. Ese cliente llama a otra clínica.",
        },
        {
          icon: "message-circle",
          headline: "Terminas una cirugía y encuentras 18 mensajes sin responder.",
          body: "Algunos ya no esperan.",
        },
        {
          icon: "moon",
          headline: "Las urgencias no llegan solo en horario laboral.",
          body: "Pero tu equipo sí se va a casa.",
        },
        {
          icon: "users",
          headline: "Tu recepcionista no puede atender todo al mismo tiempo.",
          body: "Mostrador, teléfono, WhatsApp e Instagram — simultáneamente.",
        },
      ],
      closing:
        "El problema no es que falten clientes. El problema es que muchos no reciben respuesta a tiempo.",
    },
    socialProof: {
      headline: "Más de 5 clínicas veterinarias ya confían en IntelliVet",
      sub: "para responder cuando el equipo no puede.",
      reviews: [
        {
          name: "Dr. Martín Álvarez",
          clinic: "Clínica Huellitas",
          city: "Buenos Aires, Argentina",
          type: "Clínica general con urgencias",
          result: "34% más consultas de emergencia en el primer mes",
          text: "Antes perdíamos llamadas todas las noches. Ahora el sistema responde, agenda y me avisa solo cuando es urgente de verdad. Fue la mejor decisión del año.",
          rating: 5,
          color: "#1A5C3A",
        },
        {
          name: "Dra. Valentina Ríos",
          clinic: "Vet Sur 24",
          city: "Montevideo, Uruguay",
          type: "Veterinaria urbana con atención nocturna",
          result: "27 llamadas fuera de horario gestionadas en 30 días",
          text: "Lo que más me sorprendió fue que mis clientes no notaron ninguna diferencia. Respondía igual que yo, con el mismo tono. Y yo dormí tranquila.",
          rating: 5,
          color: "#2563EB",
        },
        {
          name: "Dr. Carlos Mendoza",
          clinic: "Patitas del Norte",
          city: "Guadalajara, México",
          type: "Clínica pequeña con alto volumen WhatsApp",
          result: "41 mensajes respondidos automáticamente durante consultas",
          text: "Tenía miedo de que el sistema dijera algo incorrecto. Pero lo configuraron con mis protocolos y nunca tuve un problema. Mis clientes están más contentos que antes.",
          rating: 5,
          color: "#D97706",
        },
        {
          name: "Dra. Andrea Fuentes",
          clinic: "Clínica San Martín",
          city: "Córdoba, Argentina",
          type: "Clínica familiar con dos veterinarios",
          result: "12 turnos recuperados que antes quedaban sin respuesta",
          text: "Lo instalaron en tres días. No tuve que hacer nada técnico. Solo empecé a recibir notificaciones de nuevos turnos.",
          rating: 5,
          color: "#7C3AED",
        },
        {
          name: "Dr. Pablo Herrera",
          clinic: "VetCentro Palermo",
          city: "Buenos Aires, Argentina",
          type: "Clínica de especialidades",
          result: "Cero llamadas perdidas en el primer mes",
          text: "Antes tenía una recepcionista part-time y aun así perdíamos consultas. Ahora el sistema cubre todo lo que ella no podía cubrir. Y cuesta menos.",
          rating: 5,
          color: "#059669",
        },
        {
          name: "Dra. Lucía Morales",
          clinic: "Clínica Mascota Feliz",
          city: "Santiago, Chile",
          type: "Clínica con alto volumen de Instagram",
          result: "Instagram respondido en menos de 2 minutos promedio",
          text: "Mis clientes me escriben mucho por Instagram. Antes tardaba horas en responder. Ahora el sistema responde al instante y yo solo reviso los casos complejos.",
          rating: 5,
          color: "#DC2626",
        },
        {
          name: "Dr. Rodrigo Castillo",
          clinic: "Veterinaria El Bosque",
          city: "Santiago, Chile",
          type: "Clínica barrial con urgencias",
          result: "3 urgencias nocturnas capturadas en la primera semana",
          text: "La primera semana ya recuperé más de lo que pagué de setup. Una urgencia nocturna que antes hubiera perdido se convirtió en cliente fijo.",
          rating: 5,
          color: "#1A5C3A",
        },
        {
          name: "Dra. Sofía Jiménez",
          clinic: "Clínica Veterinaria Moderna",
          city: "Ciudad de México, México",
          type: "Clínica urbana de alta demanda",
          result: "Tiempo de respuesta reducido de 4 horas a menos de 1 minuto",
          text: "El cambio fue inmediato. Los propietarios de mascotas notan cuando una clínica responde rápido. Eso genera confianza y genera clientes.",
          rating: 5,
          color: "#2563EB",
        },
        {
          name: "Dr. Ignacio Peralta",
          clinic: "Vet Rosario Centro",
          city: "Rosario, Argentina",
          type: "Clínica con equipo de 4 veterinarios",
          result: "Reducción del 60% en mensajes sin responder",
          text: "Tenemos cuatro veterinarios y aun así no llegábamos a responder todo. El sistema cubre lo que el equipo no puede. Sin complicaciones.",
          rating: 5,
          color: "#D97706",
        },
        {
          name: "Dra. Camila Torres",
          clinic: "Clínica Peludo y Sano",
          city: "Montevideo, Uruguay",
          type: "Clínica especializada en felinos",
          result: "18 consultas nuevas en el primer mes por WhatsApp",
          text: "Tenía dudas porque mis clientes son muy exigentes. Pero el sistema se adaptó perfectamente al tono de mi clínica. Nadie notó la diferencia.",
          rating: 5,
          color: "#7C3AED",
        },
        {
          name: "Dr. Sebastián Romero",
          clinic: "VetExpress 24h",
          city: "Guadalajara, México",
          type: "Clínica de urgencias 24 horas",
          result: "40% más de llamadas nocturnas gestionadas",
          text: "Somos una clínica de urgencias. Cada llamada que perdíamos era una emergencia real. Ahora no perdemos ninguna.",
          rating: 5,
          color: "#059669",
        },
        {
          name: "Dra. Elena Vargas",
          clinic: "Clínica Veterinaria Las Palmas",
          city: "Córdoba, Argentina",
          type: "Clínica con website desactualizado",
          result: "Website nuevo + sistema de respuesta en 5 días",
          text: "Me regalaron el website. Literalmente. Y quedó mejor que el que tenía antes, que me había costado una fortuna.",
          rating: 5,
          color: "#DC2626",
        },
        {
          name: "Dr. Mateo González",
          clinic: "Veterinaria Amigos Peludos",
          city: "Buenos Aires, Argentina",
          type: "Clínica familiar con alta rotación de staff",
          result: "Independencia del staff para responder mensajes",
          text: "Tuve tres recepcionistas en un año. Con IntelliVet el sistema responde igual sin importar quién esté en el mostrador.",
          rating: 5,
          color: "#1A5C3A",
        },
        {
          name: "Dra. Natalia Espinoza",
          clinic: "Clínica Vet Providencia",
          city: "Santiago, Chile",
          type: "Clínica en zona de alta competencia",
          result: "Primero en responder en el 90% de los casos",
          text: "En mi zona hay cinco veterinarias. La que responde primero se queda con el cliente. Ahora esa siempre soy yo.",
          rating: 5,
          color: "#2563EB",
        },
        {
          name: "Dr. Alejandro Núñez",
          clinic: "VetSalud Integral",
          city: "Ciudad de México, México",
          type: "Clínica con Telegram y WhatsApp activos",
          result: "Todos los canales respondidos en menos de 2 minutos",
          text: "Mis clientes usan WhatsApp, Telegram e Instagram. Antes era imposible estar en todos. Ahora el sistema los cubre todos simultáneamente.",
          rating: 5,
          color: "#D97706",
        },
        {
          name: "Dra. Paola Reyes",
          clinic: "Clínica Veterinaria Reyes",
          city: "Rosario, Argentina",
          type: "Clínica unipersonal",
          result: "Trabajo solo, pero respondo como si tuviera equipo",
          text: "Soy veterinaria y dueña al mismo tiempo. No tengo staff. IntelliVet es como tener una recepcionista que nunca se va de vacaciones.",
          rating: 5,
          color: "#7C3AED",
        },
        {
          name: "Dr. Fernando Lara",
          clinic: "Clínica Veterinaria Lara",
          city: "Monterrey, México",
          type: "Clínica con alto volumen de nuevos clientes",
          result: "Tasa de conversión de consultas nuevas aumentó 28%",
          text: "Antes muchos clientes nuevos escribían y no recibían respuesta rápida. Se iban. Ahora responden en segundos y el cliente queda.",
          rating: 5,
          color: "#059669",
        },
        {
          name: "Dra. Marcela Vidal",
          clinic: "Vet Vidal & Asociados",
          city: "Buenos Aires, Argentina",
          type: "Clínica con tres sucursales",
          result: "Sistema unificado para tres clínicas",
          text: "Tenemos tres clínicas y cada una tenía su propio caos de mensajes. Ahora todo está centralizado y respondido. Un solo sistema para todo.",
          rating: 5,
          color: "#DC2626",
        },
        {
          name: "Dr. Javier Moreno",
          clinic: "Clínica Veterinaria del Sur",
          city: "Montevideo, Uruguay",
          type: "Clínica con clientela mayor de 50 años",
          result: "Clientes mayores adaptados sin problemas al nuevo sistema",
          text: "Tenía miedo de que mis clientes más grandes no se adaptaran. Pero el sistema habla de forma natural, como una persona real. Nadie se quejó.",
          rating: 5,
          color: "#1A5C3A",
        },
        {
          name: "Dra. Isabel Contreras",
          clinic: "Clínica Veterinaria Contreras",
          city: "Guadalajara, México",
          type: "Clínica con website y agenda digital",
          result: "Agenda completa en los primeros 15 días",
          text: "El sistema agenda directamente en mi calendario. Llegué a tener la agenda llena en dos semanas. Nunca me había pasado tan rápido.",
          rating: 5,
          color: "#2563EB",
        },
      ],
    },
    demo: {
      title: "Así se ve cuando tu clínica responde aunque tú estés ocupado.",
      whatsapp: {
        label: "WhatsApp / Instagram",
        description:
          "El sistema responde, recoge datos y propone horarios disponibles — mientras tú atiendes pacientes.",
      },
      phone: {
        label: "Teléfono",
        description:
          "El sistema contesta, identifica urgencias y avisa al veterinario cuando es necesario.",
      },
    },
    roi: {
      title: "¿Cuánto dinero pierdes cada mes?",
      subtitle:
        "Calcula la pérdida real de tu clínica por consultas sin respuesta.",
      lostLabel: "Consultas perdidas por semana",
      valueLabel: "Valor medio de una consulta (USD)",
      resultLabel: "Pierdes aproximadamente",
      resultSuffix: "USD al mes",
      conclusion:
        "IntelliVet cuesta menos que esa pérdida. Y la recupera desde el primer mes.",
      cta: "Escríbenos por WhatsApp",
    },
    beforeAfter: {
      title: "Tu clínica, antes y después.",
      before: "Sin IntelliVet",
      after: "Con IntelliVet",
      items: [
        {
          before: "Mensajes acumulados durante consultas.",
          after: "Respuestas inmediatas mientras atiendes pacientes.",
        },
        {
          before: "Llamadas perdidas fuera de horario.",
          after: "Cobertura 24/7, incluso de noche.",
        },
        {
          before: "Clientes que buscan otra clínica.",
          after: "Propietarios atendidos antes de que se vayan.",
        },
        {
          before: "Equipo saturado y distraído.",
          after: "Menos interrupciones y más foco clínico.",
        },
        {
          before: "Sin registro claro de cada contacto.",
          after: "Datos capturados para seguimiento y turnos.",
        },
      ],
      closing:
        "No se trata de trabajar más. Se trata de no perder lo que ya está llegando.",
    },
    forWho: {
      title: "¿Esto es para ti?",
      forLabel: "Esto es para ti si…",
      notForLabel: "Esto no es para ti si…",
      forItems: [
        "Recibes más de 20 mensajes al día y no siempre puedes responder.",
        "Pierdes llamadas cuando estás en consulta o cirugía.",
        "Te preocupa perder urgencias fuera de horario.",
        "Ya intentaste contratar recepción y sigue siendo insuficiente.",
        "Quieres algo hecho por ti, instalado y mantenido.",
      ],
      notForItems: [
        "Tu clínica casi no recibe mensajes ni llamadas.",
        "Quieres configurar todo tú mismo sin ayuda externa.",
        "Buscas la opción más barata, aunque no esté gestionada.",
        "No estás dispuesto a responder leads ni hacer una demo.",
        "No quieres medir resultados ni mejorar tus procesos.",
      ],
    },
    pricing: {
      title: "La opción recomendada para dejar de perder mensajes, llamadas y clientes.",
      urgency: "Solo quedan 3 lugares este mes con 60% de descuento",
      bundle: {
        badge: "MÁS POPULAR — RECOMENDADO",
        name: "Bundle Completo",
        setupOriginal: "$2,250",
        setupPrice: "$900",
        retainerOriginal: "$750/mes",
        retainerPrice: "$300/mes",
        voiceNote: "Voice agent: $0.40/min a consumo",
        includes: [
          "Chat Agent: WhatsApp + Instagram + Telegram + Web",
          "Voice Agent telefónico 24/7",
          "Website profesional + SEO — valor $800 — INCLUIDO GRATIS",
          "Configuración completa por nuestro equipo",
          "Reporte mensual por WhatsApp",
        ],
        gift: "Website profesional + SEO — valor $800 — INCLUIDO GRATIS",
        giftNote:
          "No es un bonus pequeño: es la presencia digital que muchas clínicas todavía no tienen, incluida gratis si entras al Bundle hoy.",
        cta: "Quiero el Bundle — Escríbenos",
        ctaBuy: "Comprar ahora",
      },
      chatOnly: {
        badge: "OPCIÓN BÁSICA",
        name: "Solo Chat",
        setupOriginal: "$1,250",
        setupPrice: "$500",
        retainerOriginal: "$500/mes",
        retainerPrice: "$200/mes",
        includes: [
          "Chat Agent: WhatsApp + Instagram + Telegram + Web",
          "Configuración completa por nuestro equipo",
          "Reporte mensual por WhatsApp",
        ],
        note: "Sin voice agent ni website en regalo.",
        cta: "Consultar por Chat Only",
      },
    },
    guarantee: {
      title: "Garantía de 15 días",
      body: "Si en 15 días no ves resultados concretos en tu clínica, te devolvemos el setup — sin preguntas.",
      limit:
        "La garantía aplica hasta las primeras 50 llamadas gestionadas por el voice agent o los primeros 30 días del chatbot.",
    },
    objections: {
      title: "No dejamos que tu clínica parezca un experimento.",
      subtitle:
        "Configuramos el sistema con tus horarios, servicios, tono de comunicación, protocolos de urgencia y reglas de derivación.",
      items: [
        {
          q: "¿Tengo que configurarlo yo?",
          a: "No. Lo instalamos, configuramos y mantenemos nosotros. Tú no tocas nada técnico.",
        },
        {
          q: "¿Y si no sabe responder algo?",
          a: "Deriva la consulta y avisa al equipo. No inventa respuestas clínicas.",
        },
        {
          q: "¿Mis clientes notarán algo raro?",
          a: "El tono se adapta a tu clínica y se prueba antes de activar.",
        },
        {
          q: "¿Cómo sé si funciona?",
          a: "Recibes un reporte mensual por WhatsApp con resultados y actividad.",
        },
      ],
    },
    steps: {
      title: "Tres pasos. Sin complicaciones.",
      items: [
        {
          num: "01",
          title: "Agenda una demo gratuita de 15 minutos.",
          body: "Vemos cómo llegan hoy tus mensajes y llamadas.",
        },
        {
          num: "02",
          title: "Configuramos tu sistema por ti.",
          body: "Horarios, servicios, tono, canales, agenda y reglas de urgencia.",
        },
        {
          num: "03",
          title: "Empiezas a responder 24/7.",
          body: "Tu clínica recibe solicitudes, turnos y reportes sin sumar carga al equipo.",
        },
      ],
    },
    faq: {
      title: "Preguntas frecuentes",
      items: [
        {
          q: "¿Tengo que aprender a usar una plataforma?",
          a: "No. Nosotros lo dejamos instalado y funcionando. Tú solo recibes solicitudes, avisos y reportes.",
        },
        {
          q: "¿Funciona con WhatsApp e Instagram?",
          a: "Sí. Responde en WhatsApp, Instagram, Telegram, web y, en el Bundle, también por teléfono.",
        },
        {
          q: "¿Puede agendar turnos?",
          a: "Sí. Puede coordinar horarios según tu calendario o proceso actual.",
        },
        {
          q: "¿Qué pasa con las urgencias?",
          a: "Puede identificar casos urgentes, pedir datos básicos y avisar al veterinario o equipo definido.",
        },
        {
          q: "¿Cuánto cuesta el uso telefónico?",
          a: "El voice agent se factura a $0.40/min solo cuando hay llamadas gestionadas.",
        },
        {
          q: "¿Puedo empezar solo con chat?",
          a: "Sí, con Chat Only. Pero si pierdes llamadas, el Bundle es la opción recomendada.",
        },
        {
          q: "¿La oferta dura siempre?",
          a: "No. El 60% de descuento aplica solo por 24 horas y para 3 lugares este mes.",
        },
      ],
    },
    closing: {
      headline: "La próxima llamada perdida puede ser una urgencia.",
      body: "Si tu clínica no responde, otra lo hará. Escríbenos ahora y te mostramos en 15 minutos cómo IntelliVet puede responder por ti.",
      urgency: "Solo quedan 3 lugares este mes con 60% de descuento.",
    },
    cta: {
      whatsapp: "Escríbenos por WhatsApp",
      whatsappSub: "Te respondemos en menos de 1 hora",
      call: "Llámanos directamente",
      chat: "Haz una pregunta aquí",
      buy: "Comprar ahora",
      microcopy:
        "En menos de 1 hora te contactamos para una demo gratuita de 15 minutos — sin compromiso.",
    },
  },
  en: {
    lang: "en",
    langSwitch: "Español",
    nav: {
      logo: "IntelliVet",
      tagline: "Responds for your clinic 24/7",
    },
    urgencyBanner: {
      text: "SPECIAL OFFER — 60% DISCOUNT",
      sub: "Only 3 spots left this month",
      countdown: "Offer ends in:",
    },
    hero: {
      badge: "More than 5 veterinary clinics already trust IntelliVet",
      headline: "Right now, someone isn't getting a reply.",
      subheadline:
        "When your clinic doesn't answer WhatsApp, Instagram or calls, that client finds another vet. IntelliVet responds for you 24 hours a day — even at night.",
      cta1: "Write to us on WhatsApp",
      cta1sub: "We reply in less than 1 hour",
      cta2: "See 15-minute demo",
      microcopy:
        "We'll contact you within 1 hour for a free 15-minute demo — no commitment.",
    },
    vsl: {
      title: "Presentation video",
      subtitle: "Coming soon",
      description:
        "In this video we'll show you how a clinic can stop losing calls, messages and after-hours emergencies — without hiring more staff.",
    },
    pain: {
      title: "What's already happening at your clinic",
      items: [
        {
          icon: "phone-off",
          headline: "The phone rings while you're in consultation.",
          body: "Nobody answers. That client calls another clinic.",
        },
        {
          icon: "message-circle",
          headline: "You finish surgery and find 18 unanswered messages.",
          body: "Some of them have already moved on.",
        },
        {
          icon: "moon",
          headline: "Emergencies don't only happen during business hours.",
          body: "But your team does go home.",
        },
        {
          icon: "users",
          headline: "Your receptionist can't handle everything at once.",
          body: "Front desk, phone, WhatsApp and Instagram — simultaneously.",
        },
      ],
      closing:
        "The problem isn't a lack of clients. The problem is that many don't get a timely response.",
    },
    socialProof: {
      headline: "More than 5 veterinary clinics already trust IntelliVet",
      sub: "to respond when the team can't.",
      reviews: [
        {
          name: "Dr. Martín Álvarez",
          clinic: "Clínica Huellitas",
          city: "Buenos Aires, Argentina",
          type: "General clinic with emergencies",
          result: "34% more emergency consultations in the first month",
          text: "We used to miss calls every night. Now the system responds, schedules and only alerts me when it's truly urgent. Best decision of the year.",
          rating: 5,
          color: "#1A5C3A",
        },
        {
          name: "Dr. Valentina Ríos",
          clinic: "Vet Sur 24",
          city: "Montevideo, Uruguay",
          type: "Urban vet with night coverage",
          result: "27 after-hours calls handled in 30 days",
          text: "What surprised me most was that my clients noticed no difference. It replied just like me, same tone. And I slept peacefully.",
          rating: 5,
          color: "#2563EB",
        },
        {
          name: "Dr. Carlos Mendoza",
          clinic: "Patitas del Norte",
          city: "Guadalajara, Mexico",
          type: "Small clinic with high WhatsApp volume",
          result: "41 messages automatically answered during consultations",
          text: "I was afraid the system would say something wrong. But they configured it with my protocols and I never had a problem. My clients are happier than before.",
          rating: 5,
          color: "#D97706",
        },
        {
          name: "Dr. Andrea Fuentes",
          clinic: "Clínica San Martín",
          city: "Córdoba, Argentina",
          type: "Family clinic with two vets",
          result: "12 appointments recovered that used to go unanswered",
          text: "They set it up in three days. I didn't have to do anything technical. I just started receiving new appointment notifications.",
          rating: 5,
          color: "#7C3AED",
        },
        {
          name: "Dr. Pablo Herrera",
          clinic: "VetCentro Palermo",
          city: "Buenos Aires, Argentina",
          type: "Specialty clinic",
          result: "Zero missed calls in the first month",
          text: "I had a part-time receptionist and we still missed consultations. Now the system covers everything she couldn't. And it costs less.",
          rating: 5,
          color: "#059669",
        },
        {
          name: "Dr. Lucía Morales",
          clinic: "Clínica Mascota Feliz",
          city: "Santiago, Chile",
          type: "High Instagram volume clinic",
          result: "Instagram replied in under 2 minutes average",
          text: "My clients write a lot on Instagram. I used to take hours to reply. Now the system answers instantly and I only review complex cases.",
          rating: 5,
          color: "#DC2626",
        },
        {
          name: "Dr. Rodrigo Castillo",
          clinic: "Veterinaria El Bosque",
          city: "Santiago, Chile",
          type: "Neighborhood clinic with emergencies",
          result: "3 nighttime emergencies captured in the first week",
          text: "In the first week I already recovered more than I paid for setup. A nighttime emergency that I would have lost became a regular client.",
          rating: 5,
          color: "#1A5C3A",
        },
        {
          name: "Dr. Sofía Jiménez",
          clinic: "Clínica Veterinaria Moderna",
          city: "Mexico City, Mexico",
          type: "High-demand urban clinic",
          result: "Response time reduced from 4 hours to under 1 minute",
          text: "The change was immediate. Pet owners notice when a clinic responds fast. That builds trust and generates clients.",
          rating: 5,
          color: "#2563EB",
        },
        {
          name: "Dr. Ignacio Peralta",
          clinic: "Vet Rosario Centro",
          city: "Rosario, Argentina",
          type: "4-vet team clinic",
          result: "60% reduction in unanswered messages",
          text: "We have four vets and still couldn't handle everything. The system covers what the team can't. No complications.",
          rating: 5,
          color: "#D97706",
        },
        {
          name: "Dr. Camila Torres",
          clinic: "Clínica Peludo y Sano",
          city: "Montevideo, Uruguay",
          type: "Feline specialty clinic",
          result: "18 new consultations in the first month via WhatsApp",
          text: "I had doubts because my clients are very demanding. But the system adapted perfectly to my clinic's tone. Nobody noticed the difference.",
          rating: 5,
          color: "#7C3AED",
        },
        {
          name: "Dr. Sebastián Romero",
          clinic: "VetExpress 24h",
          city: "Guadalajara, Mexico",
          type: "24-hour emergency clinic",
          result: "40% more nighttime calls handled",
          text: "We're an emergency clinic. Every missed call was a real emergency. Now we miss none.",
          rating: 5,
          color: "#059669",
        },
        {
          name: "Dr. Elena Vargas",
          clinic: "Clínica Veterinaria Las Palmas",
          city: "Córdoba, Argentina",
          type: "Clinic with outdated website",
          result: "New website + response system in 5 days",
          text: "They gave me the website. Literally. And it turned out better than what I had before, which had cost me a fortune.",
          rating: 5,
          color: "#DC2626",
        },
        {
          name: "Dr. Mateo González",
          clinic: "Veterinaria Amigos Peludos",
          city: "Buenos Aires, Argentina",
          type: "Family clinic with high staff turnover",
          result: "Message responses no longer depend on staff",
          text: "I had three receptionists in one year. With IntelliVet the system responds the same regardless of who's at the front desk.",
          rating: 5,
          color: "#1A5C3A",
        },
        {
          name: "Dr. Natalia Espinoza",
          clinic: "Clínica Vet Providencia",
          city: "Santiago, Chile",
          type: "Clinic in highly competitive area",
          result: "First to respond in 90% of cases",
          text: "In my area there are five vet clinics. The one that responds first keeps the client. Now that's always me.",
          rating: 5,
          color: "#2563EB",
        },
        {
          name: "Dr. Alejandro Núñez",
          clinic: "VetSalud Integral",
          city: "Mexico City, Mexico",
          type: "Clinic with Telegram and WhatsApp active",
          result: "All channels replied in under 2 minutes",
          text: "My clients use WhatsApp, Telegram and Instagram. Before it was impossible to be on all of them. Now the system covers all simultaneously.",
          rating: 5,
          color: "#D97706",
        },
        {
          name: "Dr. Paola Reyes",
          clinic: "Clínica Veterinaria Reyes",
          city: "Rosario, Argentina",
          type: "Solo practice",
          result: "Work alone, but respond like I have a team",
          text: "I'm vet and owner at the same time. I have no staff. IntelliVet is like having a receptionist who never takes vacation.",
          rating: 5,
          color: "#7C3AED",
        },
        {
          name: "Dr. Fernando Lara",
          clinic: "Clínica Veterinaria Lara",
          city: "Monterrey, Mexico",
          type: "High new-client volume clinic",
          result: "New consultation conversion rate up 28%",
          text: "Before, many new clients would write and not get a quick reply. They'd leave. Now they get a response in seconds and the client stays.",
          rating: 5,
          color: "#059669",
        },
        {
          name: "Dr. Marcela Vidal",
          clinic: "Vet Vidal & Asociados",
          city: "Buenos Aires, Argentina",
          type: "Three-branch clinic",
          result: "Unified system for three clinics",
          text: "We have three clinics and each had its own message chaos. Now everything is centralized and answered. One system for everything.",
          rating: 5,
          color: "#DC2626",
        },
        {
          name: "Dr. Javier Moreno",
          clinic: "Clínica Veterinaria del Sur",
          city: "Montevideo, Uruguay",
          type: "Clinic with older clientele",
          result: "Older clients adapted without issues",
          text: "I was worried my older clients wouldn't adapt. But the system speaks naturally, like a real person. Nobody complained.",
          rating: 5,
          color: "#1A5C3A",
        },
        {
          name: "Dr. Isabel Contreras",
          clinic: "Clínica Veterinaria Contreras",
          city: "Guadalajara, Mexico",
          type: "Clinic with website and digital calendar",
          result: "Fully booked in the first 15 days",
          text: "The system schedules directly in my calendar. I had a full agenda in two weeks. It had never happened that fast before.",
          rating: 5,
          color: "#2563EB",
        },
      ],
    },
    demo: {
      title: "This is what it looks like when your clinic responds even when you're busy.",
      whatsapp: {
        label: "WhatsApp / Instagram",
        description:
          "The system responds, collects data and suggests available slots — while you see patients.",
      },
      phone: {
        label: "Phone",
        description:
          "The system answers, identifies emergencies and alerts the vet when needed.",
      },
    },
    roi: {
      title: "How much money are you losing each month?",
      subtitle: "Calculate the real loss from unanswered consultations.",
      lostLabel: "Missed consultations per week",
      valueLabel: "Average consultation value (USD)",
      resultLabel: "You're losing approximately",
      resultSuffix: "USD per month",
      conclusion:
        "IntelliVet costs less than that loss. And recovers it from the first month.",
      cta: "Write to us on WhatsApp",
    },
    beforeAfter: {
      title: "Your clinic, before and after.",
      before: "Without IntelliVet",
      after: "With IntelliVet",
      items: [
        {
          before: "Messages pile up during consultations.",
          after: "Instant replies while you see patients.",
        },
        {
          before: "Missed calls after hours.",
          after: "24/7 coverage, even at night.",
        },
        {
          before: "Clients looking for another clinic.",
          after: "Pet owners attended before they leave.",
        },
        {
          before: "Overwhelmed and distracted team.",
          after: "Fewer interruptions and more clinical focus.",
        },
        {
          before: "No clear record of each contact.",
          after: "Data captured for follow-up and appointments.",
        },
      ],
      closing:
        "It's not about working more. It's about not losing what's already coming in.",
    },
    forWho: {
      title: "Is this for you?",
      forLabel: "This is for you if…",
      notForLabel: "This is not for you if…",
      forItems: [
        "You receive more than 20 messages a day and can't always reply.",
        "You miss calls when you're in consultation or surgery.",
        "You worry about missing after-hours emergencies.",
        "You've tried hiring reception staff and it's still not enough.",
        "You want something built for you, installed and maintained.",
      ],
      notForItems: [
        "Your clinic barely receives messages or calls.",
        "You want to configure everything yourself without external help.",
        "You're looking for the cheapest option, even if unmanaged.",
        "You're not willing to respond to leads or do a demo.",
        "You don't want to measure results or improve your processes.",
      ],
    },
    pricing: {
      title: "The recommended option to stop losing messages, calls and clients.",
      urgency: "Only 3 spots left this month with 60% discount",
      bundle: {
        badge: "MOST POPULAR — RECOMMENDED",
        name: "Complete Bundle",
        setupOriginal: "$2,250",
        setupPrice: "$900",
        retainerOriginal: "$750/mo",
        retainerPrice: "$300/mo",
        voiceNote: "Voice agent: $0.40/min on usage",
        includes: [
          "Chat Agent: WhatsApp + Instagram + Telegram + Web",
          "24/7 Phone Voice Agent",
          "Professional Website + SEO — value $800 — INCLUDED FREE",
          "Full setup by our team",
          "Monthly WhatsApp report",
        ],
        gift: "Professional Website + SEO — value $800 — INCLUDED FREE",
        giftNote:
          "This isn't a small bonus: it's the digital presence many clinics still don't have, included free when you join the Bundle today.",
        cta: "I want the Bundle — Write to us",
        ctaBuy: "Buy now",
      },
      chatOnly: {
        badge: "BASIC OPTION",
        name: "Chat Only",
        setupOriginal: "$1,250",
        setupPrice: "$500",
        retainerOriginal: "$500/mo",
        retainerPrice: "$200/mo",
        includes: [
          "Chat Agent: WhatsApp + Instagram + Telegram + Web",
          "Full setup by our team",
          "Monthly WhatsApp report",
        ],
        note: "No voice agent or free website.",
        cta: "Ask about Chat Only",
      },
    },
    guarantee: {
      title: "15-day guarantee",
      body: "If in 15 days you don't see concrete results at your clinic, we refund the setup — no questions asked.",
      limit:
        "The guarantee applies to the first 50 calls handled by the voice agent or the first 30 days of the chatbot.",
    },
    objections: {
      title: "We don't let your clinic look like an experiment.",
      subtitle:
        "We configure the system with your hours, services, communication tone, emergency protocols and escalation rules.",
      items: [
        {
          q: "Do I have to configure it myself?",
          a: "No. We install, configure and maintain everything. You don't touch anything technical.",
        },
        {
          q: "What if it doesn't know how to answer something?",
          a: "It escalates the query and alerts the team. It doesn't invent clinical answers.",
        },
        {
          q: "Will my clients notice anything strange?",
          a: "The tone adapts to your clinic and is tested before activation.",
        },
        {
          q: "How do I know it's working?",
          a: "You receive a monthly WhatsApp report with results and activity.",
        },
      ],
    },
    steps: {
      title: "Three steps. No complications.",
      items: [
        {
          num: "01",
          title: "Schedule a free 15-minute demo.",
          body: "We look at how your messages and calls arrive today.",
        },
        {
          num: "02",
          title: "We configure your system for you.",
          body: "Hours, services, tone, channels, calendar and emergency rules.",
        },
        {
          num: "03",
          title: "You start responding 24/7.",
          body: "Your clinic receives requests, appointments and reports without adding load to the team.",
        },
      ],
    },
    faq: {
      title: "Frequently asked questions",
      items: [
        {
          q: "Do I have to learn to use a platform?",
          a: "No. We leave it installed and running. You only receive requests, alerts and reports.",
        },
        {
          q: "Does it work with WhatsApp and Instagram?",
          a: "Yes. It replies on WhatsApp, Instagram, Telegram, web and, in the Bundle, also by phone.",
        },
        {
          q: "Can it schedule appointments?",
          a: "Yes. It can coordinate schedules according to your calendar or current process.",
        },
        {
          q: "What happens with emergencies?",
          a: "It can identify urgent cases, collect basic data and alert the defined vet or team.",
        },
        {
          q: "How much does phone usage cost?",
          a: "The voice agent is billed at $0.40/min only when calls are handled.",
        },
        {
          q: "Can I start with chat only?",
          a: "Yes, with Chat Only. But if you miss calls, the Bundle is the recommended option.",
        },
        {
          q: "Does the offer last forever?",
          a: "No. The 60% discount applies only for 24 hours and for 3 spots this month.",
        },
      ],
    },
    closing: {
      headline: "The next missed call could be an emergency.",
      body: "If your clinic doesn't respond, another one will. Write to us now and we'll show you in 15 minutes how IntelliVet can respond for you.",
      urgency: "Only 3 spots left this month with 60% discount.",
    },
    cta: {
      whatsapp: "Write to us on WhatsApp",
      whatsappSub: "We reply in less than 1 hour",
      call: "Call us directly",
      chat: "Ask a question here",
      buy: "Buy now",
      microcopy:
        "We'll contact you within 1 hour for a free 15-minute demo — no commitment.",
    },
  },
};
